### ISSUE TITLE
The Wild Hunt displayed as Number 

### ISSUE THREAD

**Issue by yoshimo** [LanceDH/WorldQuestTab#4]
The Tab shows the faction filter as number (2422) not name.
It looks better when i change the line similiar to other addons to:

`	,[2465] =	{ ["expansion"] = LE_EXPANSION_SHADOWLANDS,["playerFaction"] = nil ,["texture"] = 3641394 } -- The Wild Hunt`

**Comment by LanceDH** [comment]
2422 seems to be working fine on the PTR, where 2465 will instead only show the number.
What version are you testing on (live, PTR, beta, ..) ?

**Comment by yoshimo** [comment]
Beta 9.0.2

**Comment by LanceDH** [comment]
Curious. I'm keeping it at 2422 for now since that one works on PTR, and should be the version going to the live servers first.
Kind of a weird case that it's different between PTR and Beta, so no way of telling which one will work on live. I can only wait and see what happens.
