### ISSUE TITLE
Hovering/Clicking new Callings causes Lua errors. See description for reproduction.

### ISSUE THREAD

**Issue by LarssonMartin1998** [LanceDH/WorldQuestTab#5]
This issue is re-producable if you hover/click the Callings-protraits inside your Covenant Sanctum tab which can be opened from an icon over your minimap.

However, the error only occurs if you hover the portrait without having picked up, or talked to the NPC which holds the new quest, so before the quest has been "discovered" I guess you could say. If you see my screenshot below, the Calling furthest to the left is highlighted in a blue circle, which means I havent "discovered" it yet, and when I click it I get the error in the print screen. It also only happens when I have my "Map & Quest Log" open.

![LuaError](https://user-images.githubusercontent.com/35811847/100339650-6cd1d900-2fda-11eb-93e3-a25eba631551.png)

**Comment by wow-addon-guy** [comment]
Message: Interface\AddOns\WorldQuestTab\WorldQuestTab.lua:2141: 'for' limit must be a number
Time: Sat Nov 28 14:21:00 2020
Count: 3
Stack: Interface\AddOns\WorldQuestTab\WorldQuestTab.lua:2141: 'for' limit must be a number
[string "@Interface\AddOns\WorldQuestTab\WorldQuestTab.lua"]:2141: in function <Interface\AddOns\WorldQuestTab\WorldQuestTab.lua:2137>
[string "=[C]"]: in function `TaskPOI_OnEnter'
[string "@Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua"]:60: in function `UpdateTooltipQuestOffer'
[string "@Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua"]:39: in function `UpdateTooltip'
[string "@Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua"]:134: in function <...ddOns\Blizzard_CovenantCallings\CovenantCallings.lua:133>

Locals: poi = <unnamed> {
 0 = <userdata>
 OnLeave = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:138
 Highlight = <unnamed> {
 }
 Update = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:11
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:149
 Bang = <unnamed> {
 }
 ignoreInLayout = true
 UpdateTooltipCheckHasQuestData = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:50
 UpdateBang = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:24
 Set = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:3
 UpdateTooltipQuestOffer = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:59
 questID = 60434
 notTracked = true
 OnEnter = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:133
 calling = <table> {
 }
 UpdateTooltip = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:34
 UpdateTooltipQuestActive = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:64
 Icon = <unnamed> {
 }
 Glow = <unnamed> {
 }
 covenantData = <table> {
 }
 UpdateIcon = <function> defined @Interface\AddOns\Blizzard_CovenantCallings\CovenantCallings.lua:16
}
questInfo = <table> {
 mapInfo = <table> {
 }
 hasRewardData = true
 TryDressUpReward = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:285
 ParseRewards = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:281
 GetRewardTexture = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:353
 alwaysHide = false
 isValid = true
 questId = 60434
 OnCreate = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:160
 GetRewardCanUpgrade = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:376
 GetRewardColor = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:368
 LoadRewards = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:185
 reward = <table> {
 }
 SetMapPos = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:170
 IsExpired = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:305
 isAllyQuest = false
 IterateRewards = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:294
 time = <table> {
 }
 IsCriteria = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:381
 rewardList = <table> {
 }
 SetAsWaypoint = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:310
 GetRewardId = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:343
 GetRewardAmount = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:348
 Init = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:144
 passedFilter = true
 isDaily = true
 GetRewardQuality = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:363
 GetTitle = <function> defined @Interface\AddOns\WorldQuestTab\Dataprovider.lua:402
 GetFirstNoneAzeriteType = <function> defined @Interface\AddOns\Wor

**Comment by LanceDH** [comment]
I don't have Shadowlands atm to test, but I've uploaded a beta version to Curse that should include a fix to this error.
